---
- name: Reboot AudioCodes MP-124 via HTTP
  hosts: all
  gather_facts: no

  tasks:
    - name: Send reboot command via HTTP
      uri:
        url: "https://{{ inventory_hostname }}/WebAdmin/Reboot"
        method: POST
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        status_code: 200
        validate_certs: no
